[env.production]
name = "todo-garden-frontend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[env.production.assets]
directory = ".open-next/assets"

[env.production.vars]
# Add your environment variables here
NEXT_PUBLIC_API_URL = "https://api.bonghoaminhoaxingdep.thainm.me"

# For development/preview
[env.preview]
name = "todo-garden-frontend-preview"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[env.preview.assets]
directory = ".open-next/assets"

[env.preview.vars]
# Add your environment variables here
NEXT_PUBLIC_API_URL = "https://api.bonghoaminhoaxingdep.thainm.me"
