[env.production]
name = "todo-garden-frontend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[env.production.assets]]
bucket = ".open-next/assets"

[env.production.vars]
# Add your environment variables here
NEXT_PUBLIC_API_URL = "https://api.bonghoaminhoaxingdep.thainm.me"

# For development/preview
[env.preview]
name = "todo-garden-frontend-preview"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[env.preview.assets]]
bucket = ".open-next/assets"

[env.preview.vars]
# Add your environment variables here
# NEXT_PUBLIC_API_URL = "your-preview-api-url"
